site_name: BTC scRNA-Seq Material
site_url: https://github.com/WangLab-ComputationalBiology/btc-scrna-training
theme: 
  name: material
  features:
    - navigation.expand
  icon:
    admonition:
      note: octicons/tag-16
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - def_list
  - toc:
      permalink: "#"
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - glightbox
  - table-reader

nav:
  - 'Getting started': 
    - 'Installation': index.md
    - 'Advanced settings': advanced.md
  - Documentation: 
    #- 'Workflows and Modules': workflow-and-modules.md
    - 'Introduction to Cirro': intro-cirro.md
    - 'Command-line interface': command-line-interface.md
  - Tutorial:
    - '1. Sample and QC filtering': quality-control.md
    - '2. Dimensionality reduction and clustering': dimensionality-clustering.md
    - '3. Cell stratification and CNV Analysis': stratification-and-cnv.md
    - '4. Batch correction and evaluation': batch-correction.md
    - '5. Cell annotation': cell-annotation.md
    - '6. Cell-cell communication': cell-communcation.md
   #- '7. Cell trajectory': trajectory.md
    - '8. Malignant meta-programs': meta-programs.md
  - Contributing: contributing.md
  - FAQ: faq.md
  - About: 
    - 'License': license.md
    - 'Release Notes': release-notes.md